services:
  task_matrix_backend:
    build:
      context: ./backend
    container_name: task_matrix_backend
    restart: always
    environment:
      SERVER_PORT: ":8080"
      DB_URI: "postgresql://postgres:postgres@task_matrix_db:5432/postgres?sslmode=disable"
      MAX_IDLE_CONNS: 20
      MAX_OPEN_CONNS: 10
      ENVIRONMENT: PRODUCTION
    ports:
      - "8080:8080"

  task_matrix_frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - task_matrix_backend
    environment:
      VITE_BACKEND_URL: "https://task_matrix_backend:8080/api/v1"

  task_matrix_db:
    container_name: task_matrix_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: